### ISSUE TITLE
TurboVNC fails to open (macOS Mojave)

### ISSUE THREAD

**Issue by Golui** [TurboVNC/turbovnc#196]
Hi,

Recently TurboVNC stopped working out of the blue. This is from the most recent version.

Running macOS 10.14.6
Java:
```
java --version
java 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```

Full stacktrace:

```
main: Could not set look & feel:
main:   java.lang.NullPointerException
main: Could not set insets:
main:   java.lang.NullPointerException
java.lang.NullPointerException
	at java.desktop/sun.font.FontDesignMetrics.getDefaultFrc(FontDesignMetrics.java:158)
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:279)
	at java.desktop/sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1231)
	at java.desktop/javax.swing.JComponent.getFontMetrics(JComponent.java:1646)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.getPreferredSize(BasicLabelUI.java:246)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
	at java.desktop/javax.swing.JSlider.updateLabelUIs(JSlider.java:853)
	at java.desktop/javax.swing.JSlider.setLabelTable(JSlider.java:824)
	at java.desktop/javax.swing.JSlider.setPaintLabels(JSlider.java:1315)
	at com.turbovnc.vncviewer.OptionsDialog.<init>(OptionsDialog.java:126)
	at com.turbovnc.vncviewer.CConn.<init>(CConn.java:82)
	at com.turbovnc.vncviewer.VncViewer.run(VncViewer.java:794)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "Thread-2" java.lang.NullPointerException
	at java.desktop/sun.font.FontDesignMetrics.getDefaultFrc(FontDesignMetrics.java:158)
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:279)
	at java.desktop/sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1231)
	at java.desktop/javax.swing.JComponent.getFontMetrics(JComponent.java:1646)
	at java.desktop/javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:351)
	at java.desktop/com.apple.laf.AquaButtonUI.getPreferredSize(AquaButtonUI.java:443)
	at java.desktop/com.apple.laf.AquaButtonUI.getMinimumSize(AquaButtonUI.java:431)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1760)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.addButtonComponents(BasicOptionPaneUI.java:778)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.createButtonArea(BasicOptionPaneUI.java:711)
	at java.desktop/com.apple.laf.AquaOptionPaneUI.createButtonArea(AquaOptionPaneUI.java:53)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.installComponents(BasicOptionPaneUI.java:200)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.installUI(BasicOptionPaneUI.java:154)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.JOptionPane.setUI(JOptionPane.java:1851)
	at java.desktop/javax.swing.JOptionPane.updateUI(JOptionPane.java:1873)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1838)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1801)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1769)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1747)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1727)
	at com.turbovnc.vncviewer.VncViewer.reportException(VncViewer.java:610)
	at com.turbovnc.vncviewer.VncViewer.run(VncViewer.java:846)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by dcommander** [comment]
This happens when launching the TurboVNC Viewer app or the /opt/TurboVNC/bin/vncviewer script?

**Comment by Golui** [comment]
Both.

**Comment by dcommander** [comment]
OK, I will try to reproduce

**Comment by dcommander** [comment]
I tried TurboVNC 2.2.3 with Java 11.0.2 on macOS 10.14.6, and I can't reproduce the problem.  Can you try upgrading to Java 11.0.4?

**Comment by Golui** [comment]
Doesn't seem to occur on 11.0.4
