### ISSUE TITLE
vncviewer: exception on setting apply

### ISSUE THREAD

**Issue by Ri0n** [TurboVNC/turbovnc#49]
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.turbovnc.vncviewer.CConn.getOptions(CConn.java:1548)
        at com.turbovnc.vncviewer.OptionsDialog.actionPerformed(OptionsDialog.java:789)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)

```

Java: java-1.8.0-openjdk-amd64

**Comment by dcommander** [comment]
I tried to reproduce this under Ubuntu 16.04 and CentOS 7 using OpenJDK 1.8.0, and unfortunately I can't.  Can you provide any additional details?  The specific error is curious, because it doesn't appear from looking at the code that such an error should ever be possible at that location.

**Comment by Ri0n** [comment]
Just close this bug. I have not time to retest it.
